CREATE TABLE IF NOT EXISTS `Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(20) NOT NULL ,
  `status` VARCHAR(8) ,
  `createDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  `updateDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Currencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currencyCode` VARCHAR(3) NOT NULL ,
  `currencyName` VARCHAR(100) NOT NULL,
  `createDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  `updateDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Money` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL ,
  `currency_id` INT NOT NULL ,
  `amount` DOUBLE(10,2) ,
  `createDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  `updateDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL ,
  `currency_id` INT NOT NULL ,
  `amount` DOUBLE(10,2) ,
  `transactionType` VARCHAR(2) NOT NULL ,
  `transactionDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;