CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL ,
  `status` VARCHAR(8) ,
  `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  `update_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `currencies` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `currency_code` VARCHAR(3) NOT NULL ,
  `currency_name` VARCHAR(100) NOT NULL,
  `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  `update_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `money` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL ,
  `currency_id` BIGINT NOT NULL ,
  `amount` DOUBLE(10,2) ,
  `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  `update_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `transactions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL ,
  `currency_id` BIGINT NOT NULL ,
  `amount` DOUBLE(10,2) ,
  `transaction_type` VARCHAR(2) NOT NULL ,
  `transaction_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;