// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.server.wallet.grpc;

/**
 * Protobuf type {@code com.aldren.server.wallet.grpc.Balance}
 */
public  final class Balance extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.aldren.server.wallet.grpc.Balance)
    BalanceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Balance.newBuilder() to construct.
  private Balance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Balance() {
    money_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Balance();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Balance(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.aldren.server.wallet.grpc.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.aldren.server.wallet.grpc.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              money_ = new java.util.ArrayList<com.aldren.server.wallet.grpc.Money>();
              mutable_bitField0_ |= 0x00000001;
            }
            money_.add(
                input.readMessage(com.aldren.server.wallet.grpc.Money.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        money_ = java.util.Collections.unmodifiableList(money_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aldren.server.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_server_wallet_grpc_Balance_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aldren.server.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_server_wallet_grpc_Balance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aldren.server.wallet.grpc.Balance.class, com.aldren.server.wallet.grpc.Balance.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private com.aldren.server.wallet.grpc.User user_;
  /**
   * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
   * @return Whether the user field is set.
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
   * @return The user.
   */
  public com.aldren.server.wallet.grpc.User getUser() {
    return user_ == null ? com.aldren.server.wallet.grpc.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
   */
  public com.aldren.server.wallet.grpc.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int MONEY_FIELD_NUMBER = 2;
  private java.util.List<com.aldren.server.wallet.grpc.Money> money_;
  /**
   * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
   */
  public java.util.List<com.aldren.server.wallet.grpc.Money> getMoneyList() {
    return money_;
  }
  /**
   * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
   */
  public java.util.List<? extends com.aldren.server.wallet.grpc.MoneyOrBuilder> 
      getMoneyOrBuilderList() {
    return money_;
  }
  /**
   * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
   */
  public int getMoneyCount() {
    return money_.size();
  }
  /**
   * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
   */
  public com.aldren.server.wallet.grpc.Money getMoney(int index) {
    return money_.get(index);
  }
  /**
   * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
   */
  public com.aldren.server.wallet.grpc.MoneyOrBuilder getMoneyOrBuilder(
      int index) {
    return money_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != null) {
      output.writeMessage(1, getUser());
    }
    for (int i = 0; i < money_.size(); i++) {
      output.writeMessage(2, money_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    for (int i = 0; i < money_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, money_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aldren.server.wallet.grpc.Balance)) {
      return super.equals(obj);
    }
    com.aldren.server.wallet.grpc.Balance other = (com.aldren.server.wallet.grpc.Balance) obj;

    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!getMoneyList()
        .equals(other.getMoneyList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (getMoneyCount() > 0) {
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + getMoneyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aldren.server.wallet.grpc.Balance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aldren.server.wallet.grpc.Balance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.aldren.server.wallet.grpc.Balance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aldren.server.wallet.grpc.Balance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aldren.server.wallet.grpc.Balance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.aldren.server.wallet.grpc.Balance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.aldren.server.wallet.grpc.Balance)
      com.aldren.server.wallet.grpc.BalanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aldren.server.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_server_wallet_grpc_Balance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aldren.server.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_server_wallet_grpc_Balance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aldren.server.wallet.grpc.Balance.class, com.aldren.server.wallet.grpc.Balance.Builder.class);
    }

    // Construct using com.aldren.server.wallet.grpc.Balance.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMoneyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (moneyBuilder_ == null) {
        money_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        moneyBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aldren.server.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_server_wallet_grpc_Balance_descriptor;
    }

    @java.lang.Override
    public com.aldren.server.wallet.grpc.Balance getDefaultInstanceForType() {
      return com.aldren.server.wallet.grpc.Balance.getDefaultInstance();
    }

    @java.lang.Override
    public com.aldren.server.wallet.grpc.Balance build() {
      com.aldren.server.wallet.grpc.Balance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aldren.server.wallet.grpc.Balance buildPartial() {
      com.aldren.server.wallet.grpc.Balance result = new com.aldren.server.wallet.grpc.Balance(this);
      int from_bitField0_ = bitField0_;
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (moneyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          money_ = java.util.Collections.unmodifiableList(money_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.money_ = money_;
      } else {
        result.money_ = moneyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aldren.server.wallet.grpc.Balance) {
        return mergeFrom((com.aldren.server.wallet.grpc.Balance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aldren.server.wallet.grpc.Balance other) {
      if (other == com.aldren.server.wallet.grpc.Balance.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (moneyBuilder_ == null) {
        if (!other.money_.isEmpty()) {
          if (money_.isEmpty()) {
            money_ = other.money_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMoneyIsMutable();
            money_.addAll(other.money_);
          }
          onChanged();
        }
      } else {
        if (!other.money_.isEmpty()) {
          if (moneyBuilder_.isEmpty()) {
            moneyBuilder_.dispose();
            moneyBuilder_ = null;
            money_ = other.money_;
            bitField0_ = (bitField0_ & ~0x00000001);
            moneyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMoneyFieldBuilder() : null;
          } else {
            moneyBuilder_.addAllMessages(other.money_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.aldren.server.wallet.grpc.Balance parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.aldren.server.wallet.grpc.Balance) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.aldren.server.wallet.grpc.User user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aldren.server.wallet.grpc.User, com.aldren.server.wallet.grpc.User.Builder, com.aldren.server.wallet.grpc.UserOrBuilder> userBuilder_;
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     * @return The user.
     */
    public com.aldren.server.wallet.grpc.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.aldren.server.wallet.grpc.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     */
    public Builder setUser(com.aldren.server.wallet.grpc.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     */
    public Builder setUser(
        com.aldren.server.wallet.grpc.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     */
    public Builder mergeUser(com.aldren.server.wallet.grpc.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.aldren.server.wallet.grpc.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     */
    public com.aldren.server.wallet.grpc.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     */
    public com.aldren.server.wallet.grpc.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.aldren.server.wallet.grpc.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aldren.server.wallet.grpc.User, com.aldren.server.wallet.grpc.User.Builder, com.aldren.server.wallet.grpc.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aldren.server.wallet.grpc.User, com.aldren.server.wallet.grpc.User.Builder, com.aldren.server.wallet.grpc.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private java.util.List<com.aldren.server.wallet.grpc.Money> money_ =
      java.util.Collections.emptyList();
    private void ensureMoneyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        money_ = new java.util.ArrayList<com.aldren.server.wallet.grpc.Money>(money_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aldren.server.wallet.grpc.Money, com.aldren.server.wallet.grpc.Money.Builder, com.aldren.server.wallet.grpc.MoneyOrBuilder> moneyBuilder_;

    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public java.util.List<com.aldren.server.wallet.grpc.Money> getMoneyList() {
      if (moneyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(money_);
      } else {
        return moneyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public int getMoneyCount() {
      if (moneyBuilder_ == null) {
        return money_.size();
      } else {
        return moneyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public com.aldren.server.wallet.grpc.Money getMoney(int index) {
      if (moneyBuilder_ == null) {
        return money_.get(index);
      } else {
        return moneyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder setMoney(
        int index, com.aldren.server.wallet.grpc.Money value) {
      if (moneyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoneyIsMutable();
        money_.set(index, value);
        onChanged();
      } else {
        moneyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder setMoney(
        int index, com.aldren.server.wallet.grpc.Money.Builder builderForValue) {
      if (moneyBuilder_ == null) {
        ensureMoneyIsMutable();
        money_.set(index, builderForValue.build());
        onChanged();
      } else {
        moneyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder addMoney(com.aldren.server.wallet.grpc.Money value) {
      if (moneyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoneyIsMutable();
        money_.add(value);
        onChanged();
      } else {
        moneyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder addMoney(
        int index, com.aldren.server.wallet.grpc.Money value) {
      if (moneyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoneyIsMutable();
        money_.add(index, value);
        onChanged();
      } else {
        moneyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder addMoney(
        com.aldren.server.wallet.grpc.Money.Builder builderForValue) {
      if (moneyBuilder_ == null) {
        ensureMoneyIsMutable();
        money_.add(builderForValue.build());
        onChanged();
      } else {
        moneyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder addMoney(
        int index, com.aldren.server.wallet.grpc.Money.Builder builderForValue) {
      if (moneyBuilder_ == null) {
        ensureMoneyIsMutable();
        money_.add(index, builderForValue.build());
        onChanged();
      } else {
        moneyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder addAllMoney(
        java.lang.Iterable<? extends com.aldren.server.wallet.grpc.Money> values) {
      if (moneyBuilder_ == null) {
        ensureMoneyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, money_);
        onChanged();
      } else {
        moneyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder clearMoney() {
      if (moneyBuilder_ == null) {
        money_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        moneyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public Builder removeMoney(int index) {
      if (moneyBuilder_ == null) {
        ensureMoneyIsMutable();
        money_.remove(index);
        onChanged();
      } else {
        moneyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public com.aldren.server.wallet.grpc.Money.Builder getMoneyBuilder(
        int index) {
      return getMoneyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public com.aldren.server.wallet.grpc.MoneyOrBuilder getMoneyOrBuilder(
        int index) {
      if (moneyBuilder_ == null) {
        return money_.get(index);  } else {
        return moneyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public java.util.List<? extends com.aldren.server.wallet.grpc.MoneyOrBuilder> 
         getMoneyOrBuilderList() {
      if (moneyBuilder_ != null) {
        return moneyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(money_);
      }
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public com.aldren.server.wallet.grpc.Money.Builder addMoneyBuilder() {
      return getMoneyFieldBuilder().addBuilder(
          com.aldren.server.wallet.grpc.Money.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public com.aldren.server.wallet.grpc.Money.Builder addMoneyBuilder(
        int index) {
      return getMoneyFieldBuilder().addBuilder(
          index, com.aldren.server.wallet.grpc.Money.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aldren.server.wallet.grpc.Money money = 2;</code>
     */
    public java.util.List<com.aldren.server.wallet.grpc.Money.Builder> 
         getMoneyBuilderList() {
      return getMoneyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aldren.server.wallet.grpc.Money, com.aldren.server.wallet.grpc.Money.Builder, com.aldren.server.wallet.grpc.MoneyOrBuilder> 
        getMoneyFieldBuilder() {
      if (moneyBuilder_ == null) {
        moneyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aldren.server.wallet.grpc.Money, com.aldren.server.wallet.grpc.Money.Builder, com.aldren.server.wallet.grpc.MoneyOrBuilder>(
                money_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        money_ = null;
      }
      return moneyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.aldren.server.wallet.grpc.Balance)
  }

  // @@protoc_insertion_point(class_scope:com.aldren.server.wallet.grpc.Balance)
  private static final com.aldren.server.wallet.grpc.Balance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aldren.server.wallet.grpc.Balance();
  }

  public static com.aldren.server.wallet.grpc.Balance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Balance>
      PARSER = new com.google.protobuf.AbstractParser<Balance>() {
    @java.lang.Override
    public Balance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Balance(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Balance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Balance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aldren.server.wallet.grpc.Balance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

