// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.server.wallet.grpc;

public final class WalletServiceOuterClass {
  private WalletServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_Money_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_Money_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_Balance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_Balance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023WalletService.proto\022\035com.aldren.server" +
      ".wallet.grpc\"\026\n\004User\022\016\n\006userId\030\001 \001(\t\")\n\005" +
      "Money\022\016\n\006amount\030\001 \001(\001\022\020\n\010currency\030\002 \001(\t\"" +
      "u\n\013UserRequest\0221\n\004user\030\001 \001(\0132#.com.aldre" +
      "n.server.wallet.grpc.User\0223\n\005money\030\002 \001(\013" +
      "2$.com.aldren.server.wallet.grpc.Money\"q" +
      "\n\007Balance\0221\n\004user\030\001 \001(\0132#.com.aldren.ser" +
      "ver.wallet.grpc.User\0223\n\005money\030\002 \003(\0132$.co" +
      "m.aldren.server.wallet.grpc.Money\"\035\n\014Use" +
      "rResponse\022\r\n\005error\030\001 \001(\t2\265\002\n\rWalletServi" +
      "ce\022b\n\007deposit\022*.com.aldren.server.wallet" +
      ".grpc.UserRequest\032+.com.aldren.server.wa" +
      "llet.grpc.UserResponse\022c\n\010withdraw\022*.com" +
      ".aldren.server.wallet.grpc.UserRequest\032+" +
      ".com.aldren.server.wallet.grpc.UserRespo" +
      "nse\022[\n\014checkBalance\022#.com.aldren.server." +
      "wallet.grpc.User\032&.com.aldren.server.wal" +
      "let.grpc.BalanceB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_aldren_server_wallet_grpc_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aldren_server_wallet_grpc_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_User_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_aldren_server_wallet_grpc_Money_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_aldren_server_wallet_grpc_Money_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_Money_descriptor,
        new java.lang.String[] { "Amount", "Currency", });
    internal_static_com_aldren_server_wallet_grpc_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_aldren_server_wallet_grpc_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_UserRequest_descriptor,
        new java.lang.String[] { "User", "Money", });
    internal_static_com_aldren_server_wallet_grpc_Balance_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_aldren_server_wallet_grpc_Balance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_Balance_descriptor,
        new java.lang.String[] { "User", "Money", });
    internal_static_com_aldren_server_wallet_grpc_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_aldren_server_wallet_grpc_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_UserResponse_descriptor,
        new java.lang.String[] { "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
