spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: iamaldren
    password: secretpasswor
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
grpc:
  port: 6565
eureka:
  instance:
    nonSecurePort: ${grpc.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/