spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aldren
    username: iamaldren
    password: secretpassword
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect