// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.server.wallet.grpc;

public interface WalletRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aldren.server.wallet.grpc.WalletRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
   * @return The user.
   */
  com.aldren.server.wallet.grpc.User getUser();
  /**
   * <code>.com.aldren.server.wallet.grpc.User user = 1;</code>
   */
  com.aldren.server.wallet.grpc.UserOrBuilder getUserOrBuilder();

  /**
   * <code>.com.aldren.server.wallet.grpc.Money money = 2;</code>
   * @return Whether the money field is set.
   */
  boolean hasMoney();
  /**
   * <code>.com.aldren.server.wallet.grpc.Money money = 2;</code>
   * @return The money.
   */
  com.aldren.server.wallet.grpc.Money getMoney();
  /**
   * <code>.com.aldren.server.wallet.grpc.Money money = 2;</code>
   */
  com.aldren.server.wallet.grpc.MoneyOrBuilder getMoneyOrBuilder();
}
