// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.server.wallet.grpc;

public final class WalletServiceOuterClass {
  private WalletServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_Money_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_Money_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_WalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_WalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_Balance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_Balance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_Currency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_Currency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aldren_server_wallet_grpc_Transactions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aldren_server_wallet_grpc_Transactions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023WalletService.proto\022\035com.aldren.server" +
      ".wallet.grpc\"\026\n\004User\022\016\n\006userId\030\001 \001(\t\")\n\005" +
      "Money\022\016\n\006amount\030\001 \001(\001\022\020\n\010currency\030\002 \001(\t\"" +
      "w\n\rWalletRequest\0221\n\004user\030\001 \001(\0132#.com.ald" +
      "ren.server.wallet.grpc.User\0223\n\005money\030\002 \001" +
      "(\0132$.com.aldren.server.wallet.grpc.Money" +
      "\"q\n\007Balance\0221\n\004user\030\001 \001(\0132#.com.aldren.s" +
      "erver.wallet.grpc.User\0223\n\005money\030\002 \003(\0132$." +
      "com.aldren.server.wallet.grpc.Money\"\007\n\005E" +
      "mpty\"&\n\010Currency\022\014\n\004code\030\001 \001(\t\022\014\n\004name\030\002" +
      " \001(\t\"K\n\013Transaction\022\016\n\006amount\030\001 \001(\001\022\020\n\010c" +
      "urrency\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\014\n\004date\030\004 \001(" +
      "\t\"\202\001\n\014Transactions\0221\n\004user\030\001 \001(\0132#.com.a" +
      "ldren.server.wallet.grpc.User\022?\n\013transac" +
      "tion\030\002 \003(\0132*.com.aldren.server.wallet.gr" +
      "pc.Transaction2\222\003\n\rWalletService\022]\n\007depo" +
      "sit\022,.com.aldren.server.wallet.grpc.Wall" +
      "etRequest\032$.com.aldren.server.wallet.grp" +
      "c.Empty\022^\n\010withdraw\022,.com.aldren.server." +
      "wallet.grpc.WalletRequest\032$.com.aldren.s" +
      "erver.wallet.grpc.Empty\022[\n\014checkBalance\022" +
      "#.com.aldren.server.wallet.grpc.User\032&.c" +
      "om.aldren.server.wallet.grpc.Balance\022e\n\021" +
      "checkTransactions\022#.com.aldren.server.wa" +
      "llet.grpc.User\032+.com.aldren.server.walle" +
      "t.grpc.Transactions2\277\001\n\013UserService\022W\n\nc" +
      "reateUser\022#.com.aldren.server.wallet.grp" +
      "c.User\032$.com.aldren.server.wallet.grpc.E" +
      "mpty\022W\n\ndeleteUser\022#.com.aldren.server.w" +
      "allet.grpc.User\032$.com.aldren.server.wall" +
      "et.grpc.Empty2\323\001\n\017CurrencyService\022_\n\016cre" +
      "ateCurrency\022\'.com.aldren.server.wallet.g" +
      "rpc.Currency\032$.com.aldren.server.wallet." +
      "grpc.Empty\022_\n\016deleteCurrency\022\'.com.aldre" +
      "n.server.wallet.grpc.Currency\032$.com.aldr" +
      "en.server.wallet.grpc.EmptyB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_aldren_server_wallet_grpc_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aldren_server_wallet_grpc_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_User_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_aldren_server_wallet_grpc_Money_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_aldren_server_wallet_grpc_Money_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_Money_descriptor,
        new java.lang.String[] { "Amount", "Currency", });
    internal_static_com_aldren_server_wallet_grpc_WalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_aldren_server_wallet_grpc_WalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_WalletRequest_descriptor,
        new java.lang.String[] { "User", "Money", });
    internal_static_com_aldren_server_wallet_grpc_Balance_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_aldren_server_wallet_grpc_Balance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_Balance_descriptor,
        new java.lang.String[] { "User", "Money", });
    internal_static_com_aldren_server_wallet_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_aldren_server_wallet_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_com_aldren_server_wallet_grpc_Currency_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_aldren_server_wallet_grpc_Currency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_Currency_descriptor,
        new java.lang.String[] { "Code", "Name", });
    internal_static_com_aldren_server_wallet_grpc_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_aldren_server_wallet_grpc_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_Transaction_descriptor,
        new java.lang.String[] { "Amount", "Currency", "Type", "Date", });
    internal_static_com_aldren_server_wallet_grpc_Transactions_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_aldren_server_wallet_grpc_Transactions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aldren_server_wallet_grpc_Transactions_descriptor,
        new java.lang.String[] { "User", "Transaction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
