// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.wallet.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aldren.wallet.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
