// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.wallet.grpc;

public interface MoneyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aldren.wallet.grpc.Money)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double amount = 1;</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>string currency = 2;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 2;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();
}
