// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.wallet.grpc;

public interface TransactionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aldren.wallet.grpc.Transactions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   * @return The user.
   */
  com.aldren.wallet.grpc.User getUser();
  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   */
  com.aldren.wallet.grpc.UserOrBuilder getUserOrBuilder();

  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  java.util.List<com.aldren.wallet.grpc.Transaction> 
      getTransactionList();
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  com.aldren.wallet.grpc.Transaction getTransaction(int index);
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  int getTransactionCount();
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  java.util.List<? extends com.aldren.wallet.grpc.TransactionOrBuilder> 
      getTransactionOrBuilderList();
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  com.aldren.wallet.grpc.TransactionOrBuilder getTransactionOrBuilder(
      int index);
}
