// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.wallet.grpc;

/**
 * Protobuf type {@code com.aldren.wallet.grpc.Transactions}
 */
public  final class Transactions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.aldren.wallet.grpc.Transactions)
    TransactionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Transactions.newBuilder() to construct.
  private Transactions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Transactions() {
    transaction_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Transactions();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Transactions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.aldren.wallet.grpc.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.aldren.wallet.grpc.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              transaction_ = new java.util.ArrayList<com.aldren.wallet.grpc.Transaction>();
              mutable_bitField0_ |= 0x00000001;
            }
            transaction_.add(
                input.readMessage(com.aldren.wallet.grpc.Transaction.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        transaction_ = java.util.Collections.unmodifiableList(transaction_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_Transactions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_Transactions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aldren.wallet.grpc.Transactions.class, com.aldren.wallet.grpc.Transactions.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private com.aldren.wallet.grpc.User user_;
  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   * @return Whether the user field is set.
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   * @return The user.
   */
  public com.aldren.wallet.grpc.User getUser() {
    return user_ == null ? com.aldren.wallet.grpc.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   */
  public com.aldren.wallet.grpc.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int TRANSACTION_FIELD_NUMBER = 2;
  private java.util.List<com.aldren.wallet.grpc.Transaction> transaction_;
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  public java.util.List<com.aldren.wallet.grpc.Transaction> getTransactionList() {
    return transaction_;
  }
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  public java.util.List<? extends com.aldren.wallet.grpc.TransactionOrBuilder> 
      getTransactionOrBuilderList() {
    return transaction_;
  }
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  public int getTransactionCount() {
    return transaction_.size();
  }
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  public com.aldren.wallet.grpc.Transaction getTransaction(int index) {
    return transaction_.get(index);
  }
  /**
   * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
   */
  public com.aldren.wallet.grpc.TransactionOrBuilder getTransactionOrBuilder(
      int index) {
    return transaction_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != null) {
      output.writeMessage(1, getUser());
    }
    for (int i = 0; i < transaction_.size(); i++) {
      output.writeMessage(2, transaction_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    for (int i = 0; i < transaction_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, transaction_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aldren.wallet.grpc.Transactions)) {
      return super.equals(obj);
    }
    com.aldren.wallet.grpc.Transactions other = (com.aldren.wallet.grpc.Transactions) obj;

    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!getTransactionList()
        .equals(other.getTransactionList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (getTransactionCount() > 0) {
      hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aldren.wallet.grpc.Transactions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.Transactions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.aldren.wallet.grpc.Transactions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aldren.wallet.grpc.Transactions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aldren.wallet.grpc.Transactions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.aldren.wallet.grpc.Transactions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.aldren.wallet.grpc.Transactions)
      com.aldren.wallet.grpc.TransactionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_Transactions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_Transactions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aldren.wallet.grpc.Transactions.class, com.aldren.wallet.grpc.Transactions.Builder.class);
    }

    // Construct using com.aldren.wallet.grpc.Transactions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransactionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (transactionBuilder_ == null) {
        transaction_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        transactionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_Transactions_descriptor;
    }

    @java.lang.Override
    public com.aldren.wallet.grpc.Transactions getDefaultInstanceForType() {
      return com.aldren.wallet.grpc.Transactions.getDefaultInstance();
    }

    @java.lang.Override
    public com.aldren.wallet.grpc.Transactions build() {
      com.aldren.wallet.grpc.Transactions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aldren.wallet.grpc.Transactions buildPartial() {
      com.aldren.wallet.grpc.Transactions result = new com.aldren.wallet.grpc.Transactions(this);
      int from_bitField0_ = bitField0_;
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (transactionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          transaction_ = java.util.Collections.unmodifiableList(transaction_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transaction_ = transaction_;
      } else {
        result.transaction_ = transactionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aldren.wallet.grpc.Transactions) {
        return mergeFrom((com.aldren.wallet.grpc.Transactions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aldren.wallet.grpc.Transactions other) {
      if (other == com.aldren.wallet.grpc.Transactions.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (transactionBuilder_ == null) {
        if (!other.transaction_.isEmpty()) {
          if (transaction_.isEmpty()) {
            transaction_ = other.transaction_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransactionIsMutable();
            transaction_.addAll(other.transaction_);
          }
          onChanged();
        }
      } else {
        if (!other.transaction_.isEmpty()) {
          if (transactionBuilder_.isEmpty()) {
            transactionBuilder_.dispose();
            transactionBuilder_ = null;
            transaction_ = other.transaction_;
            bitField0_ = (bitField0_ & ~0x00000001);
            transactionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionFieldBuilder() : null;
          } else {
            transactionBuilder_.addAllMessages(other.transaction_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.aldren.wallet.grpc.Transactions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.aldren.wallet.grpc.Transactions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.aldren.wallet.grpc.User user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aldren.wallet.grpc.User, com.aldren.wallet.grpc.User.Builder, com.aldren.wallet.grpc.UserOrBuilder> userBuilder_;
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     * @return The user.
     */
    public com.aldren.wallet.grpc.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.aldren.wallet.grpc.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public Builder setUser(com.aldren.wallet.grpc.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public Builder setUser(
        com.aldren.wallet.grpc.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public Builder mergeUser(com.aldren.wallet.grpc.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.aldren.wallet.grpc.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public com.aldren.wallet.grpc.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public com.aldren.wallet.grpc.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.aldren.wallet.grpc.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aldren.wallet.grpc.User, com.aldren.wallet.grpc.User.Builder, com.aldren.wallet.grpc.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aldren.wallet.grpc.User, com.aldren.wallet.grpc.User.Builder, com.aldren.wallet.grpc.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private java.util.List<com.aldren.wallet.grpc.Transaction> transaction_ =
      java.util.Collections.emptyList();
    private void ensureTransactionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        transaction_ = new java.util.ArrayList<com.aldren.wallet.grpc.Transaction>(transaction_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aldren.wallet.grpc.Transaction, com.aldren.wallet.grpc.Transaction.Builder, com.aldren.wallet.grpc.TransactionOrBuilder> transactionBuilder_;

    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public java.util.List<com.aldren.wallet.grpc.Transaction> getTransactionList() {
      if (transactionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transaction_);
      } else {
        return transactionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public int getTransactionCount() {
      if (transactionBuilder_ == null) {
        return transaction_.size();
      } else {
        return transactionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public com.aldren.wallet.grpc.Transaction getTransaction(int index) {
      if (transactionBuilder_ == null) {
        return transaction_.get(index);
      } else {
        return transactionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder setTransaction(
        int index, com.aldren.wallet.grpc.Transaction value) {
      if (transactionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionIsMutable();
        transaction_.set(index, value);
        onChanged();
      } else {
        transactionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder setTransaction(
        int index, com.aldren.wallet.grpc.Transaction.Builder builderForValue) {
      if (transactionBuilder_ == null) {
        ensureTransactionIsMutable();
        transaction_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder addTransaction(com.aldren.wallet.grpc.Transaction value) {
      if (transactionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionIsMutable();
        transaction_.add(value);
        onChanged();
      } else {
        transactionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder addTransaction(
        int index, com.aldren.wallet.grpc.Transaction value) {
      if (transactionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionIsMutable();
        transaction_.add(index, value);
        onChanged();
      } else {
        transactionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder addTransaction(
        com.aldren.wallet.grpc.Transaction.Builder builderForValue) {
      if (transactionBuilder_ == null) {
        ensureTransactionIsMutable();
        transaction_.add(builderForValue.build());
        onChanged();
      } else {
        transactionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder addTransaction(
        int index, com.aldren.wallet.grpc.Transaction.Builder builderForValue) {
      if (transactionBuilder_ == null) {
        ensureTransactionIsMutable();
        transaction_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder addAllTransaction(
        java.lang.Iterable<? extends com.aldren.wallet.grpc.Transaction> values) {
      if (transactionBuilder_ == null) {
        ensureTransactionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transaction_);
        onChanged();
      } else {
        transactionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder clearTransaction() {
      if (transactionBuilder_ == null) {
        transaction_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        transactionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public Builder removeTransaction(int index) {
      if (transactionBuilder_ == null) {
        ensureTransactionIsMutable();
        transaction_.remove(index);
        onChanged();
      } else {
        transactionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public com.aldren.wallet.grpc.Transaction.Builder getTransactionBuilder(
        int index) {
      return getTransactionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public com.aldren.wallet.grpc.TransactionOrBuilder getTransactionOrBuilder(
        int index) {
      if (transactionBuilder_ == null) {
        return transaction_.get(index);  } else {
        return transactionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public java.util.List<? extends com.aldren.wallet.grpc.TransactionOrBuilder> 
         getTransactionOrBuilderList() {
      if (transactionBuilder_ != null) {
        return transactionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transaction_);
      }
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public com.aldren.wallet.grpc.Transaction.Builder addTransactionBuilder() {
      return getTransactionFieldBuilder().addBuilder(
          com.aldren.wallet.grpc.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public com.aldren.wallet.grpc.Transaction.Builder addTransactionBuilder(
        int index) {
      return getTransactionFieldBuilder().addBuilder(
          index, com.aldren.wallet.grpc.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aldren.wallet.grpc.Transaction transaction = 2;</code>
     */
    public java.util.List<com.aldren.wallet.grpc.Transaction.Builder> 
         getTransactionBuilderList() {
      return getTransactionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aldren.wallet.grpc.Transaction, com.aldren.wallet.grpc.Transaction.Builder, com.aldren.wallet.grpc.TransactionOrBuilder> 
        getTransactionFieldBuilder() {
      if (transactionBuilder_ == null) {
        transactionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aldren.wallet.grpc.Transaction, com.aldren.wallet.grpc.Transaction.Builder, com.aldren.wallet.grpc.TransactionOrBuilder>(
                transaction_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        transaction_ = null;
      }
      return transactionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.aldren.wallet.grpc.Transactions)
  }

  // @@protoc_insertion_point(class_scope:com.aldren.wallet.grpc.Transactions)
  private static final com.aldren.wallet.grpc.Transactions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aldren.wallet.grpc.Transactions();
  }

  public static com.aldren.wallet.grpc.Transactions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Transactions>
      PARSER = new com.google.protobuf.AbstractParser<Transactions>() {
    @java.lang.Override
    public Transactions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Transactions(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Transactions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Transactions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aldren.wallet.grpc.Transactions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

