// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package com.aldren.wallet.grpc;

/**
 * Protobuf type {@code com.aldren.wallet.grpc.WalletRequest}
 */
public  final class WalletRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.aldren.wallet.grpc.WalletRequest)
    WalletRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WalletRequest.newBuilder() to construct.
  private WalletRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WalletRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WalletRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WalletRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.aldren.wallet.grpc.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.aldren.wallet.grpc.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.aldren.wallet.grpc.Money.Builder subBuilder = null;
            if (money_ != null) {
              subBuilder = money_.toBuilder();
            }
            money_ = input.readMessage(com.aldren.wallet.grpc.Money.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(money_);
              money_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_WalletRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_WalletRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aldren.wallet.grpc.WalletRequest.class, com.aldren.wallet.grpc.WalletRequest.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private com.aldren.wallet.grpc.User user_;
  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   * @return Whether the user field is set.
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   * @return The user.
   */
  public com.aldren.wallet.grpc.User getUser() {
    return user_ == null ? com.aldren.wallet.grpc.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.com.aldren.wallet.grpc.User user = 1;</code>
   */
  public com.aldren.wallet.grpc.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int MONEY_FIELD_NUMBER = 2;
  private com.aldren.wallet.grpc.Money money_;
  /**
   * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
   * @return Whether the money field is set.
   */
  public boolean hasMoney() {
    return money_ != null;
  }
  /**
   * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
   * @return The money.
   */
  public com.aldren.wallet.grpc.Money getMoney() {
    return money_ == null ? com.aldren.wallet.grpc.Money.getDefaultInstance() : money_;
  }
  /**
   * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
   */
  public com.aldren.wallet.grpc.MoneyOrBuilder getMoneyOrBuilder() {
    return getMoney();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != null) {
      output.writeMessage(1, getUser());
    }
    if (money_ != null) {
      output.writeMessage(2, getMoney());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    if (money_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMoney());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aldren.wallet.grpc.WalletRequest)) {
      return super.equals(obj);
    }
    com.aldren.wallet.grpc.WalletRequest other = (com.aldren.wallet.grpc.WalletRequest) obj;

    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (hasMoney() != other.hasMoney()) return false;
    if (hasMoney()) {
      if (!getMoney()
          .equals(other.getMoney())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (hasMoney()) {
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + getMoney().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aldren.wallet.grpc.WalletRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aldren.wallet.grpc.WalletRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aldren.wallet.grpc.WalletRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.aldren.wallet.grpc.WalletRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.aldren.wallet.grpc.WalletRequest)
      com.aldren.wallet.grpc.WalletRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_WalletRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_WalletRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aldren.wallet.grpc.WalletRequest.class, com.aldren.wallet.grpc.WalletRequest.Builder.class);
    }

    // Construct using com.aldren.wallet.grpc.WalletRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (moneyBuilder_ == null) {
        money_ = null;
      } else {
        money_ = null;
        moneyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aldren.wallet.grpc.WalletServiceOuterClass.internal_static_com_aldren_wallet_grpc_WalletRequest_descriptor;
    }

    @java.lang.Override
    public com.aldren.wallet.grpc.WalletRequest getDefaultInstanceForType() {
      return com.aldren.wallet.grpc.WalletRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.aldren.wallet.grpc.WalletRequest build() {
      com.aldren.wallet.grpc.WalletRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aldren.wallet.grpc.WalletRequest buildPartial() {
      com.aldren.wallet.grpc.WalletRequest result = new com.aldren.wallet.grpc.WalletRequest(this);
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (moneyBuilder_ == null) {
        result.money_ = money_;
      } else {
        result.money_ = moneyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aldren.wallet.grpc.WalletRequest) {
        return mergeFrom((com.aldren.wallet.grpc.WalletRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aldren.wallet.grpc.WalletRequest other) {
      if (other == com.aldren.wallet.grpc.WalletRequest.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.hasMoney()) {
        mergeMoney(other.getMoney());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.aldren.wallet.grpc.WalletRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.aldren.wallet.grpc.WalletRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.aldren.wallet.grpc.User user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aldren.wallet.grpc.User, com.aldren.wallet.grpc.User.Builder, com.aldren.wallet.grpc.UserOrBuilder> userBuilder_;
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     * @return The user.
     */
    public com.aldren.wallet.grpc.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.aldren.wallet.grpc.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public Builder setUser(com.aldren.wallet.grpc.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public Builder setUser(
        com.aldren.wallet.grpc.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public Builder mergeUser(com.aldren.wallet.grpc.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.aldren.wallet.grpc.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public com.aldren.wallet.grpc.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    public com.aldren.wallet.grpc.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.aldren.wallet.grpc.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.com.aldren.wallet.grpc.User user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aldren.wallet.grpc.User, com.aldren.wallet.grpc.User.Builder, com.aldren.wallet.grpc.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aldren.wallet.grpc.User, com.aldren.wallet.grpc.User.Builder, com.aldren.wallet.grpc.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private com.aldren.wallet.grpc.Money money_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aldren.wallet.grpc.Money, com.aldren.wallet.grpc.Money.Builder, com.aldren.wallet.grpc.MoneyOrBuilder> moneyBuilder_;
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     * @return Whether the money field is set.
     */
    public boolean hasMoney() {
      return moneyBuilder_ != null || money_ != null;
    }
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     * @return The money.
     */
    public com.aldren.wallet.grpc.Money getMoney() {
      if (moneyBuilder_ == null) {
        return money_ == null ? com.aldren.wallet.grpc.Money.getDefaultInstance() : money_;
      } else {
        return moneyBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     */
    public Builder setMoney(com.aldren.wallet.grpc.Money value) {
      if (moneyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        money_ = value;
        onChanged();
      } else {
        moneyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     */
    public Builder setMoney(
        com.aldren.wallet.grpc.Money.Builder builderForValue) {
      if (moneyBuilder_ == null) {
        money_ = builderForValue.build();
        onChanged();
      } else {
        moneyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     */
    public Builder mergeMoney(com.aldren.wallet.grpc.Money value) {
      if (moneyBuilder_ == null) {
        if (money_ != null) {
          money_ =
            com.aldren.wallet.grpc.Money.newBuilder(money_).mergeFrom(value).buildPartial();
        } else {
          money_ = value;
        }
        onChanged();
      } else {
        moneyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     */
    public Builder clearMoney() {
      if (moneyBuilder_ == null) {
        money_ = null;
        onChanged();
      } else {
        money_ = null;
        moneyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     */
    public com.aldren.wallet.grpc.Money.Builder getMoneyBuilder() {
      
      onChanged();
      return getMoneyFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     */
    public com.aldren.wallet.grpc.MoneyOrBuilder getMoneyOrBuilder() {
      if (moneyBuilder_ != null) {
        return moneyBuilder_.getMessageOrBuilder();
      } else {
        return money_ == null ?
            com.aldren.wallet.grpc.Money.getDefaultInstance() : money_;
      }
    }
    /**
     * <code>.com.aldren.wallet.grpc.Money money = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.aldren.wallet.grpc.Money, com.aldren.wallet.grpc.Money.Builder, com.aldren.wallet.grpc.MoneyOrBuilder> 
        getMoneyFieldBuilder() {
      if (moneyBuilder_ == null) {
        moneyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.aldren.wallet.grpc.Money, com.aldren.wallet.grpc.Money.Builder, com.aldren.wallet.grpc.MoneyOrBuilder>(
                getMoney(),
                getParentForChildren(),
                isClean());
        money_ = null;
      }
      return moneyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.aldren.wallet.grpc.WalletRequest)
  }

  // @@protoc_insertion_point(class_scope:com.aldren.wallet.grpc.WalletRequest)
  private static final com.aldren.wallet.grpc.WalletRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aldren.wallet.grpc.WalletRequest();
  }

  public static com.aldren.wallet.grpc.WalletRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WalletRequest>
      PARSER = new com.google.protobuf.AbstractParser<WalletRequest>() {
    @java.lang.Override
    public WalletRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WalletRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WalletRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WalletRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aldren.wallet.grpc.WalletRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

